title: visual-increment.vim
description: Use CTRL+A/X to create increasing sequence of numbers or letters via visual mode
google_analytics: "<script> \tvar _gaq=[['_setAccount','UA-30556434-1'],['_trackPageview']]; \t(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0]; \tg.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js'; \ts.parentNode.insertBefore(g,s)}(document,'script')); </script> "
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
